a = 5
b = 'hello'
c = '3'
print(f'{type(a) = }')
print(f'{type(b) = }')
print(f'{type(c) = }')
print(f'{a * 5 = }')
print(f'{b * 5 = }')
print(f'{c * 5 = }')  # strongly typed, string operation
print(f'{a + c = }')  # strongly typed, TypeError exception
